### ISSUE TITLE
[Autorooms] Empty channels sometimes aren't deleted

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#30]
Sometimes channels won't get deleted.  I don't know how, exaclty, as I haven't been able to reproduce it myself, but there was one empty room today that I think was an accident and then the other day someone deliberately triggered that glitch to spam a hundred empty voice channels.  They didn't do anything funky with the permissions because it didn't show up in the audit log, it was just Red.

I don't know if there needs to be a periodic check to purge all empty auto channels or what.

**Comment by mikeshardmind** [comment]
Are you also using the temp channels cog, or is this definitely the auto-rooms causing it?

**Comment by HelmicNewciv** [comment]
Definitely not using the temp channels cog. I'm not at my desk, but I can do some troubleshooting later this week if that will help you.

**Comment by mikeshardmind** [comment]
I'll take a closer look at it after work tomorrow, I'll also add a purge command tomorrow that will remove all empty autorooms as a bit of convenience. I'd like to say I'll have the issue fixed tomorrow, but realistically, I probably won't.

**Comment by mikeshardmind** [comment]
This should be fixed now. In the case of any future issues, there are two new commands:

[p]autoroomset purge
[p]autoroomset purgeall

(purge only removes the empty cloned rooms, purgeall removes all of them)

Let me know if you encounter anymore issues with this.

**Comment by HelmicNewciv** [comment]
I'm unable to load the cog. I can't double check what's going on in the console currently, but restarting Red doesn't fix it. Can't update Red itself either right now so that might be the issue, but just mentioning this in case there's an "oh wait duh" moment.

**Comment by mikeshardmind** [comment]
`[p]cog update` when you get a chance.... I added my docstrings after testing and inadvertently misplaced them breaking what I had just tested.

**Comment by HelmicNewciv** [comment]
Yep, that works. Going to see if I find any more duplicate channels.
